version: '3'
services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: dev_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mariadb:
    image: mariadb:10.4
    container_name: dev_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABSE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: dev_php
    volumes:
      - ./src:/var/www/html
      - ./php/php-ini-oeverrides.ini:/etc/php/7.2/frm/conf.d/php-ini-overrides.ini
    ports:
      - "9000:9000"
